name: eslint-backend-nodejs-ci

on:
  push:
  pull_request:
  pull_request_review:
    types:
      - dismissed

jobs:
  eslint-backend-lint-coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ '12', '14', '16' ]

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: Use Node.js - ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # for cache-hit's
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        run: yarn --frozen-lockfile --prefer-offline
      - name: Run Linter
        run: yarn lint
